# Generated by Django 6.0.4 on 2026-04-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('objective', models.TextField()),
                ('skills', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('profile', models.URLField()),
            ],
        ),
    ]
