# Generated by Django 6.0.4 on 2026-04-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
